---
title: "Data Tidying"
author: "AB"
date: "1/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
# load packages  
library(dplyr)  
library(tidyr) 
# Produces warning about masking functions with same names in different packages. R assumes most recently added package first. Use 'package_name::function_name(...)' to specify that the other package's function should be used. Add warning = FALSE and message = FALSE to suppress warnings. 
```

# Data Cleaning 

Read in the data.

```{r}
catch <- read.csv(file = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", 
                  stringsAsFactors = FALSE)  
head(catch)  
```


Keyboard shortcut for pipe operator cmd + shift + m  

```{r}
catch_long <- catch %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% 
  gather(key = "species", value = "catch", -Year, -Region)  
head(catch_long)
```
Select to remove unnecessary columns (marginal sum and notes column). Gather to reformat from wide to long format. Collected species into one species column while keeping Region and Year fields intact. 
Data tidying in progress...  

# Split-Apply-Combine  

# Joins  